apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
spec:
  replicas: 3
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        type: proxy-server
    spec:
      containers:
      - name: nginx-container
        image: nginx
